// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA1VqfUHK92yG-URWW5hmBnzpeiHnZBLc',
    appId: '1:491295598063:android:eef717787024397b03821a',
    messagingSenderId: '491295598063',
    projectId: 'niigma-ai',
    storageBucket: 'niigma-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-U47vdNFLaDo3l2Ir3zkpuqg1_2jk_Sg',
    appId: '1:491295598063:ios:2f39eaa11a650e4d03821a',
    messagingSenderId: '491295598063',
    projectId: 'niigma-ai',
    storageBucket: 'niigma-ai.firebasestorage.app',
    iosBundleId: 'com.niigma.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEoeA9IVB-x9AeQXjb-bzhK2Wzo4bo1vQ',
    appId: '1:491295598063:web:a750ca70f883e79503821a',
    messagingSenderId: '491295598063',
    projectId: 'niigma-ai',
    authDomain: 'niigma-ai.firebaseapp.com',
    storageBucket: 'niigma-ai.firebasestorage.app',
    measurementId: 'G-KMVPEMP0ER',
  );
}
